# -*- coding: utf-8 -*-
"""pipeline-analise-financeira-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GMhq1akX9b3TeVbrGhxA0l_Ho_qXQ0i
"""

# Pipeline de Análise Financeira
# Autora: Ana Luiza de Souza Gomes

import pandas as pd

def carregar_dados():
    try:
        df = pd.read_csv('financeiro_pipeline.csv')
        print("Dados carregados com sucesso.")
        return df
    except Exception as e:
        print(f"Erro ao carregar dados: {e}")
        return None

def limpar_dados(df):
    print("\nLimpando dados...")
    df = df.dropna()  # remove valores nulos
    return df

def validar_dados(df):
    print("Validando dados...")
    erros = df[df['status'] != 'ok']
    if not erros.empty:
        print("Registros com inconsistência encontrados:")
        print(erros)
    return df[df['status'] == 'ok']

def analisar_dados(df):
    print("\nAnalisando dados...")
    total = df['valor'].sum()
    media = df['valor'].mean()

    print(f"Total: R$ {total}")
    print(f"Média: R$ {media:.2f}")

    return total, media

def gerar_relatorio(df):
    print("\nGerando relatório...")
    df.to_csv('relatorio_pipeline.csv', index=False)
    print("Relatório gerado com sucesso!")

def main():
    df = carregar_dados()

    if df is not None:
        df = limpar_dados(df)
        df = validar_dados(df)
        analisar_dados(df)
        gerar_relatorio(df)

if __name__ == "__main__":
    main()

from google.colab import files
uploaded = files.upload()